### ISSUE TITLE
There is no documentation for the project.

### ISSUE THREAD

**Issue by bruce-forte** [brice-morin/kosm#2]
I don't know how to use it. The project should at least have a getting started with a few examples.

**Comment by brice-morin** [comment]
Hi,

Yes indeed. I will try to write a getting started document. Note that this project is a bit old now, and I am not too sure what was the status when I stopped the developments. But it is a good opportunity to try to refresh it.

**Comment by brice-morin** [comment]
Actually, it is a set of tests that give example for most of the concepts of this framework. I updated the readme to point to this folder. Note that I haven't updates this repo for some years, so I have no idea at this point if it still works with the latest version of Kotlin. But the Kotlin version put in the pom.xml should hopefully still work as it worked some years ago...
